security:
    password_hashers:
        App\Entity\U:
            algorithm: auto

       
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\U
                property: email
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        # 'main' is the name of the firewall (can be chosen freely)
        main:
            # 'pattern' is a regular expression matched against the incoming
            # request URL. If there's a match, authentication is triggered
            pattern: ^/admin
            custom_authenticator:
               
                - App\Security\LoginAuthenticator
               
            logout:
                path: app_logout
                # where to redirect after logout
                target: /fon/o
            # the rest of options depend on the authentication mechanism
            # ...


 
   