index:
    path: /
    controller: App\Controller\DefaultController::index

orange:
    path: /orange
    controller: App\Controller\OrangebController::index

acceuil:
    path: /acceuil
    controller: App\Controller\AcceuilController::index

bordeaux:
     path: /orange/bordeaux
     controller: App\Controller\StructuresController::index
          
lille:
     path: /orange/lille
     controller: App\Controller\OrangeLilleController::index

marseille:
     path: /orange/marseille
     controller: App\Controller\OrangeMarseilleController::index
     

fonc:
     path: /fon/o
     controller: App\Controller\FonOController::index

partenaires:
     path: '/partner/o'
     controller: App\Controller\PartnerOController::index

partenaires_show:
     path: '/{id}'
     controller: App\Controller\PartnerOController::index
     requirements:
      id: '\d+'

partenaires_add:
     path: '/new'
     controller: App\Controller\PartnerOController::index

partenaires_edit:
     path: '/{id}/edit'
     controller: App\Controller\PartnerOController::index
     requirements:
      id: '\d+'
  
partenaires_remove:
     path: '/{id}'
     controller: App\Controller\PartnerOController::index
     requirements:
      id: '\d+'

structures:
     path: /structures
     controller: App\Controller\StructureController::index

structures_show:
     path: '/{id}'
     controller: App\Controller\StructureController::index
     requirements:
      id: '\d+'

structures_add:
     path: '/new'
     controller: App\Controller\StructureController::index

structures_edit:
     path: '/{id}/edit'
     controller: App\Controller\StructureController::index
     requirements:
      id: '\d+'
  
structures_remove:
     path: '/{id}'
     controller: App\Controller\StructureController::index
     requirements:
      id: '\d+'


permission:
     path: /permission
     controller: App\Controller\PermissionController::index

app_permission_show:
     path: '/{id}'
     controller: App\Controller\PermissionController::index
     requirements:
      id: '\d+'

app_permission_new:
     path: '/new'
     controller: App\Controller\PermissionController::index

app_permission_edit:
     path: '/{id}/edit'
     controller: App\Controller\PermissionController::index
     requirements:
      id: '\d+'
  
app_permission_remove:
     path: '/{id}'
     controller: App\Controller\PermissionController::index
     requirements:
      id: '\d+'

app_login:
path: /login
     controller: App\Controller\SecurityController::index
rechercher:
    path:  /search
    controller: App\Controller\SearchController::index









    

